import { describe, expect, it } from 'vitest'
import { analyse } from '../engine/analyse'
import { buildDemoDataset } from '../demo/dataset'
import { applyDemoStages } from '../demo/stages'
import { DEFAULT_SETTINGS, type Analysis, type Finding, type Workspace } from '../engine/types'
import { emptyData, type WorkspaceData } from '../data/backend'
import { METHODOLOGY, aiSentence, annualSentence, buildReport, headlineSentence, rowRanges, sourcesOf } from './report'

// The demo workspace through the real engine, as the store builds it.
function demo(): { ws: Workspace; analysis: Analysis; data: WorkspaceData } {
  const uploads = {
    clients: { id: 'u-clients', file_name: 'clients.csv' },
    tickets: { id: 'u-tickets', file_name: 'tickets.csv' },
    time_entries: { id: 'u-time', file_name: 'time-entries.csv' },
    assets: { id: 'u-assets', file_name: 'users-and-devices.csv' },
    billing: { id: 'u-billing', file_name: 'billing.csv' },
  }
  const ds = buildDemoDataset('ws', uploads)
  const { summary, findings: drafts } = analyse(ds)
  const at = '2026-10-01T09:00:00.000Z'
  const analysis: Analysis = { id: 'a1b2c3d4-0000-0000-0000-000000000000', workspace_id: 'ws', period_start: summary.period_start, period_end: summary.period_end, summary, created_at: at }
  let findings: Finding[] = drafts.map((d, i) => ({ ...d, id: `f${i}`, workspace_id: 'ws', analysis_id: analysis.id, status: 'open', ai_explanation: null, created_at: at, updated_at: at }))
  const name = (id: string) => ds.clients.find((c) => c.id === id)?.name ?? ''
  const stages = new Map(applyDemoStages(findings, name).map((s) => [s.id, s]))
  findings = findings.map((f) => (stages.has(f.id) ? { ...f, status: stages.get(f.id)!.status } : f))
  const ws: Workspace = { id: 'ws', name: 'Northlight IT', settings: DEFAULT_SETTINGS, is_demo: true, created_at: at } as Workspace
  return { ws, analysis, data: { ...emptyData(), clients: ds.clients, findings } }
}

describe('buildReport (demo)', () => {
  const { ws, analysis, data } = demo()
  const r = buildReport(ws, analysis, data)

  it('keeps the pinned figures and leads with the conservative split', () => {
    expect(r.total).toBe(4281)
    expect(r.monthly).toBe(356)
    expect(r.annual).toBe(4272)
    expect(r.findingCount).toBe(40)
    expect(r.agreementValue).toBe(143220)
    expect(r.split.high.value).toBe(1405)
    expect(r.split.review.value).toBe(2876)
    expect(r.split.high.value + r.split.review.value).toBe(r.total)
    expect(headlineSentence(r)).toContain('£1,405 is high-confidence opportunity')
  })

  it('backs every opportunity with an evidence row that adds up to the total', () => {
    expect(r.evidence).toHaveLength(40)
    expect(r.evidence.reduce((a, e) => a + e.value, 0)).toBe(r.total)
    expect(r.evidence.map((e) => e.ref)).toEqual(r.evidence.map((_, i) => `E${i + 1}`))
    for (const b of r.breakdown) expect(r.evidence.filter((e) => e.category === b.category).reduce((a, e) => a + e.value, 0)).toBe(b.value)
    for (const s of r.sections) expect(s.rows.reduce((a, e) => a + e.value, 0) + (s.more?.value ?? 0)).toBe(s.value)
    for (const e of r.evidence) {
      expect(e.calc.length, e.title).toBeGreaterThan(0)
      expect(e.sources.length, e.title).toBeGreaterThan(0)
      expect(e.action, e.title).not.toBe('')
      expect(e.basis, e.title).not.toBe('')
    }
    // Every category, not only the three the old report listed.
    expect(r.sections.map((s) => s.key).sort()).toEqual([...new Set(data.findings.map((f) => f.category))].sort())
  })

  it('shows the drift working and traces it to file and row', () => {
    const drift = r.evidence.find((e) => e.category === 'AGREEMENT_DRIFT' && e.client === 'ABC Ltd' && e.title.includes('users'))!
    expect(drift.calc[0]).toBe('39 active users − 35 contracted and billed = 4 users')
    expect(drift.calc[1]).toContain('4 × £18')
    expect(drift.calc[2]).toBe('£72 × 12 = £864 a year')
    expect(drift.sources.find((s) => s.source === 'Agreement')?.detail).toContain('section 1.2')
    expect(drift.sources.find((s) => s.source === 'Asset register')?.detail).toMatch(/^users-and-devices\.csv, rows \d/)
    expect(drift.sources.find((s) => s.source === 'Billing')?.detail).toMatch(/^billing\.csv, row \d+$/)
    expect(drift.level).toBe('HIGH')
    expect(drift.classification).toBe('confirmed')
  })

  it('states stages, methodology and the AI boundary', () => {
    expect(r.stages.reduce((a, s) => a + s.count, 0)).toBe(40)
    expect(r.stages.find((s) => s.status === 'valid')!.count).toBeGreaterThan(0)
    expect(METHODOLOGY[0]).toBe(
      'Findings are generated by comparing customer-provided operational, contractual and billing data. Financial calculations are deterministic. Contract interpretation and classification may use AI-assisted analysis. Findings should be reviewed by the MSP before billing or contractual changes are made.',
    )
    expect(aiSentence(r)).toContain('No figure in this report was produced by AI')
    expect(aiSentence(r)).not.toContain('AI assists with interpretation')
    expect(r.ai.explained).toBe(0)
    expect(annualSentence(r)).toContain('£4,272')
  })

  it('never prints the numeric confidence score or the old leakage wording', () => {
    // profitability carries the engine's ClientMetrics field names, which are never printed.
    const text = JSON.stringify({ ...r, profitability: undefined, clientName: undefined })
    expect(text).not.toMatch(/"confidence":\s*\d/)
    expect(text.toLowerCase()).not.toContain('leakage')
    expect(text).not.toMatch(/owes|—/)
  })

  it('includes an AI explanation only when it is current, and labels it', () => {
    const f = data.findings[0]
    const withAi = { ...data, findings: data.findings.map((x) => (x.id === f.id ? { ...x, ai_explanation: 'Plain-English summary.', ai_meta: { model: 'm', generated_at: '2026-10-02T10:00:00Z', evidence_hash: 'x' } } : x)) }
    expect(buildReport(ws, analysis, withAi).ai.explained).toBe(0)
    const shown = buildReport(ws, analysis, withAi, { aiCurrent: new Set([f.id]) })
    expect(shown.ai.explained).toBe(1)
    expect(aiSentence(shown)).toContain('AI-assisted explanation')
  })
})

describe('source lines', () => {
  it('folds rows into ranges', () => {
    expect(rowRanges([5, 2, 3, 4, 9, 11, 10])).toBe('2–5, 9–11')
  })
  it('keeps records without a file honest', () => {
    const lines = sourcesOf({ source_data: [{ table: 'tickets', id: 't1', label: 'Ticket #1' }], evidence: [] })
    expect(lines).toEqual([{ source: 'PSA', detail: 'Ticket #1 (no source file recorded)' }])
  })
})
