// Generated by src/pages/landing/writeSnapshot.ts from the demo dataset and the
// real engine. Do not edit by hand: run `npx tsx src/pages/landing/writeSnapshot.ts`.
// demoSnapshot.test.ts fails if this drifts from the engine.
import type { LandingSnapshot } from './snapshotTypes'

export const DEMO: LandingSnapshot = {
  "msp": "Northlight IT",
  "period": {
    "label": "April to September 2026",
    "months": 6,
    "first": "2026-04",
    "last": "2026-09"
  },
  "totals": {
    "identified": 4281,
    "monthly": 356,
    "annual": 4272,
    "findings": 40,
    "clients": 15,
    "atRisk": 4,
    "billed": 143220
  },
  "data": {
    "clients": 15,
    "tickets": 1061,
    "timeEntries": 1278,
    "usersAndDevices": 793,
    "billingLines": 75,
    "contracts": 15
  },
  "settings": {
    "labourRate": 35,
    "billableRate": 60,
    "targetMargin": 0.3
  },
  "categories": [
    {
      "category": "OUT_OF_SCOPE",
      "value": 1240,
      "count": 12,
      "clients": 7
    },
    {
      "category": "AGREEMENT_DRIFT",
      "value": 1120,
      "count": 6,
      "clients": 6
    },
    {
      "category": "UNBILLED_TIME",
      "value": 840,
      "count": 17,
      "clients": 10
    },
    {
      "category": "UNDERPRICED_CLIENT",
      "value": 681,
      "count": 3,
      "clients": 3
    },
    {
      "category": "EXCESSIVE_USAGE",
      "value": 355,
      "count": 1,
      "clients": 1
    },
    {
      "category": "MISSING_LICENSE",
      "value": 45,
      "count": 1,
      "clients": 1
    }
  ],
  "topFindings": [
    {
      "title": "Support usage above the 10h monthly allowance",
      "client": "Harbour Physio",
      "category": "EXCESSIVE_USAGE",
      "severity": "HIGH",
      "confidence": 88,
      "value": 355,
      "monthly": 0,
      "ticketRef": null,
      "workDate": null
    },
    {
      "title": "Gross margin 28% against a 30% target",
      "client": "ABC Ltd",
      "category": "UNDERPRICED_CLIENT",
      "severity": "HIGH",
      "confidence": 82,
      "value": 336,
      "monthly": 56,
      "ticketRef": null,
      "workDate": null
    },
    {
      "title": "4 more users than contracted",
      "client": "ABC Ltd",
      "category": "AGREEMENT_DRIFT",
      "severity": "HIGH",
      "confidence": 95,
      "value": 324,
      "monthly": 72,
      "ticketRef": null,
      "workDate": null
    },
    {
      "title": "3 more users than contracted",
      "client": "Riverside Care Group",
      "category": "AGREEMENT_DRIFT",
      "severity": "HIGH",
      "confidence": 95,
      "value": 270,
      "monthly": 54,
      "ticketRef": null,
      "workDate": null
    },
    {
      "title": "5 more devices than contracted",
      "client": "Meridian Logistics",
      "category": "AGREEMENT_DRIFT",
      "severity": "HIGH",
      "confidence": 95,
      "value": 240,
      "monthly": 40,
      "ticketRef": null,
      "workDate": null
    }
  ],
  "recurring": {
    "count": 10,
    "rows": [
      {
        "title": "4 more users than contracted",
        "client": "ABC Ltd",
        "category": "AGREEMENT_DRIFT",
        "severity": "HIGH",
        "confidence": 95,
        "value": 324,
        "monthly": 72,
        "ticketRef": null,
        "workDate": null
      },
      {
        "title": "3 more users than contracted",
        "client": "Riverside Care Group",
        "category": "AGREEMENT_DRIFT",
        "severity": "HIGH",
        "confidence": 95,
        "value": 270,
        "monthly": 54,
        "ticketRef": null,
        "workDate": null
      },
      {
        "title": "5 more devices than contracted",
        "client": "Meridian Logistics",
        "category": "AGREEMENT_DRIFT",
        "severity": "HIGH",
        "confidence": 95,
        "value": 240,
        "monthly": 40,
        "ticketRef": null,
        "workDate": null
      },
      {
        "title": "4 more devices than contracted",
        "client": "Dorset Legal",
        "category": "AGREEMENT_DRIFT",
        "severity": "HIGH",
        "confidence": 95,
        "value": 168,
        "monthly": 28,
        "ticketRef": null,
        "workDate": null
      }
    ]
  },
  "leaks": {
    "scope": {
      "finding": {
        "title": "Out-of-hours work not charged",
        "client": "Meridian Logistics",
        "category": "OUT_OF_SCOPE",
        "severity": "HIGH",
        "confidence": 90,
        "value": 150,
        "monthly": 0,
        "ticketRef": "18177",
        "workDate": "2026-09-09T21:40:00"
      },
      "subject": "Out of hours: warehouse scanner system down",
      "body": "Night shift could not scan. Remote session to restart handheld scanner service and print server.",
      "ticketHighlights": [
        "Out of hours"
      ],
      "clause": "Support is available between 08:30 and 17:30, Monday to Friday, excluding UK bank holidays.",
      "clauseHighlights": [
        "Support is available between 08:30 and 17:30, Monday"
      ],
      "contractTitle": "Managed Services Agreement – Business Pro",
      "time": {
        "date": "2026-09-09",
        "time": "21:40",
        "technician": "Tom Walker",
        "duration": "1h 40m",
        "billable": false
      }
    },
    "unbilled": {
      "finding": {
        "title": "Billable ticket with non-billable time",
        "client": "Elmfield Dental",
        "category": "UNBILLED_TIME",
        "severity": "MEDIUM",
        "confidence": 92,
        "value": 70,
        "monthly": 0,
        "ticketRef": "18094",
        "workDate": "2026-08-26T09:15:00"
      },
      "subject": "Install additional surgery workstation",
      "body": "Quoted and approved. Installed workstation in surgery 4.",
      "ticketHighlights": [],
      "clause": null,
      "clauseHighlights": [],
      "contractTitle": null,
      "time": {
        "date": "2026-08-26",
        "time": "09:15",
        "technician": "Priya Patel",
        "duration": "1h 10m",
        "billable": false
      }
    },
    "drift": {
      "finding": {
        "title": "3 more users than contracted",
        "client": "Riverside Care Group",
        "category": "AGREEMENT_DRIFT",
        "severity": "HIGH",
        "confidence": 95,
        "value": 270,
        "monthly": 54,
        "ticketRef": null,
        "workDate": null
      },
      "contracted": 40,
      "active": 43,
      "unitPrice": 18
    },
    "underpriced": {
      "finding": {
        "title": "Gross margin 28% against a 30% target",
        "client": "Castle Accountancy",
        "category": "UNDERPRICED_CLIENT",
        "severity": "HIGH",
        "confidence": 82,
        "value": 229,
        "monthly": 38,
        "ticketRef": null,
        "workDate": null
      },
      "mrr": 1500,
      "avgHours": 26.4,
      "margin": 0.284
    }
  },
  "outOfScope": {
    "count": 12,
    "value": 1240,
    "rows": [
      {
        "title": "Personal device supported free of charge",
        "client": "Willow & Hart Interiors",
        "category": "OUT_OF_SCOPE",
        "severity": "HIGH",
        "confidence": 90,
        "value": 60,
        "monthly": 0,
        "ticketRef": "18285",
        "workDate": "2026-09-28T11:30:00"
      },
      {
        "title": "Personal device supported free of charge",
        "client": "Bramley Homes",
        "category": "OUT_OF_SCOPE",
        "severity": "HIGH",
        "confidence": 94,
        "value": 80,
        "monthly": 0,
        "ticketRef": "18492",
        "workDate": "2026-09-15T10:20:00"
      },
      {
        "title": "Third-party application support given free",
        "client": "Kingsbridge Architects",
        "category": "OUT_OF_SCOPE",
        "severity": "HIGH",
        "confidence": 90,
        "value": 150,
        "monthly": 0,
        "ticketRef": "18189",
        "workDate": "2026-09-11T09:30:00"
      },
      {
        "title": "Out-of-hours work not charged",
        "client": "Meridian Logistics",
        "category": "OUT_OF_SCOPE",
        "severity": "HIGH",
        "confidence": 90,
        "value": 150,
        "monthly": 0,
        "ticketRef": "18177",
        "workDate": "2026-09-09T21:40:00"
      },
      {
        "title": "Hardware repair done as non-billable",
        "client": "Bramley Homes",
        "category": "OUT_OF_SCOPE",
        "severity": "HIGH",
        "confidence": 94,
        "value": 95,
        "monthly": 0,
        "ticketRef": "18049",
        "workDate": "2026-08-19T11:30:00"
      },
      {
        "title": "Third-party application support given free",
        "client": "Castle Accountancy",
        "category": "OUT_OF_SCOPE",
        "severity": "HIGH",
        "confidence": 90,
        "value": 75,
        "monthly": 0,
        "ticketRef": "18017",
        "workDate": "2026-08-13T14:15:00"
      },
      {
        "title": "Onsite visit not charged",
        "client": "Pennine Engineering",
        "category": "OUT_OF_SCOPE",
        "severity": "HIGH",
        "confidence": 90,
        "value": 120,
        "monthly": 0,
        "ticketRef": "17965",
        "workDate": "2026-08-04T12:30:00"
      },
      {
        "title": "Out-of-hours work not charged",
        "client": "Meridian Logistics",
        "category": "OUT_OF_SCOPE",
        "severity": "HIGH",
        "confidence": 90,
        "value": 90,
        "monthly": 0,
        "ticketRef": "17872",
        "workDate": "2026-07-18T10:05:00"
      }
    ]
  },
  "spotlight": {
    "finding": {
      "title": "Personal device supported free of charge",
      "client": "Bramley Homes",
      "category": "OUT_OF_SCOPE",
      "severity": "HIGH",
      "confidence": 94,
      "value": 80,
      "monthly": 0,
      "ticketRef": "18492",
      "workDate": "2026-09-15T10:20:00"
    },
    "subject": "Set up employee's personal MacBook",
    "body": "Sales negotiator asked us to configure her personal MacBook with Outlook, Teams and the shared drive so she can work from it. Installed Company Portal, configured mail and OneDrive, mapped drives.",
    "ticketHighlights": [
      "personal MacBook",
      "employee's personal MacBook"
    ],
    "clause": "Support applies to company-owned devices only.",
    "clauseHighlights": [
      "applies to company-owned devices"
    ],
    "contractTitle": "Managed Services Agreement – Business Essentials",
    "time": {
      "date": "2026-09-15",
      "time": "10:20",
      "technician": "James Smith",
      "duration": "1h 20m",
      "billable": false
    },
    "recommendedAction": "Review whether this work on a personal device should be treated as out of scope and charged at your standard rate (£60/h). If it's a recurring request, agree how it will be billed with Bramley Homes."
  },
  "client": {
    "name": "ABC Ltd",
    "package": "Business Pro",
    "mrr": 1850,
    "avgHours": 25.9,
    "monthlyHours": [
      {
        "month": "Apr",
        "hours": 22
      },
      {
        "month": "May",
        "hours": 24
      },
      {
        "month": "Jun",
        "hours": 26
      },
      {
        "month": "Jul",
        "hours": 27
      },
      {
        "month": "Aug",
        "hours": 28
      },
      {
        "month": "Sep",
        "hours": 28.6
      }
    ],
    "labour": 908,
    "software": 420,
    "contribution": 522,
    "margin": 0.282,
    "users": 39,
    "contractedUsers": 35,
    "devices": 42,
    "contractedDevices": 42,
    "health": "at_risk",
    "leakage": 740,
    "findings": [
      {
        "title": "Gross margin 28% against a 30% target",
        "client": "ABC Ltd",
        "category": "UNDERPRICED_CLIENT",
        "severity": "HIGH",
        "confidence": 82,
        "value": 336,
        "monthly": 56,
        "ticketRef": null,
        "workDate": null
      },
      {
        "title": "4 more users than contracted",
        "client": "ABC Ltd",
        "category": "AGREEMENT_DRIFT",
        "severity": "HIGH",
        "confidence": 95,
        "value": 324,
        "monthly": 72,
        "ticketRef": null,
        "workDate": null
      },
      {
        "title": "Potentially billable project work logged as non-billable",
        "client": "ABC Ltd",
        "category": "UNBILLED_TIME",
        "severity": "MEDIUM",
        "confidence": 65,
        "value": 80,
        "monthly": 0,
        "ticketRef": "18110",
        "workDate": "2026-08-27T13:30:00"
      }
    ],
    "recommended": 1897,
    "uplift": 47,
    "driftMonthly": 72,
    "mrrAfterDrift": 1922,
    "marginAfterDrift": 0.309
  }
}
